* 2.2の練習問題
** 問題2.2.1
*** a)
1. aはSである
2. aa+は,S S +によりSである
3. S S *によりaa+a*はSである。
*** b)
#+NAME: 解析木
#+BEGIN_SRC emacs-lisp 
  '(S
    (S 
     (S a) 
     (S a) 
     +) 
    (S a) 
    *)
#+END_SRC       
*** c)
aと+と*の記号で、構成され、+記号と、*記号を演算子として後置構文的な文法を構成する。
S S +と、S S *という文法本体によって、後置的なる。

** 問題2.2.2
*** a) S -> 0 S 1 | 0 1
0と1が1<nの任意の自然数n個の0が並び、n個の1が並ぶ。
S1 = 01
S2 = 0011
S3 = 000111
のように、0がn個、1がn個ならぶとき、Snと表現する。 
1. n = 1のときは
生成規則の本体の右側により。01はSである。
2. n = k (kは1以上の任意の自然数)のとき、SkがSであるとする。
すると、0Sk1 がSであり、これは、S(k+1)でもあるので、S(k+1)はSである。 
よって、1,2により、Snは、Sである。

*** b) S -> + S S | - S S | a
+と-のみの、前置記法の言語である。
本体の+ S Sと- S S によって前置記法を構成する。

*** c) S -> S ( S ) S | e
()()や(())() のようなやつ。

*** d) S -> a S b S | b S a S | e
空および、aとbが同じ回数だけ出てくる文法。
Lnをaとbがn回でてくる言語とする。
1) L0はeのみの集合なので、L0はSの部分集合、
2) Lk (k任意の自然数)とき LkはSの部分集合であるならば
Lkの任意の要素をxとすると
abx
axb
xab
bax
bxa
xba
すべてがL(k+1)の要素であることを示したらよい。
1)abxは、a S1 b S2 よりS1 = e, S2 = xとおけば導出できる
2) axbは S1 = x, S2 = eにより導出できる
xabは、x = a'x または、x = b'xと分かれる
とするとa'xabまたは、b'xabと分かれる
よって、a('xa)bとb('xa)bとなり、
'xaもまたLkの要素であり、2により導出が可能
abは対照的なので、のこりも同様に導出ができるのでLkはSに含まれる。
また、Lは絶対にa,b以外の記号が出てこない。また、どの文法規則も、aとbは同じ回数出現するので、aとbの出現は同数となうる。
よって、LNはSである。

*** e) S -> a | S + S | S S | S * | (S)
aが任意の数出てきて、+は2項演算子、*は後置単項演算子、(S)でネストできる言語。
S + Sにより、+は2項演算子S *により後置演算子、(S)により、ネスト

** 問題2.2.3
*** a,bは曖昧ではない
*** c). 
たとえば、()()のとき

#+NAME: 解析木
#+BEGIN_SRC emacs-lisp 
'(S (S (S e) "(" (S e) ")" (S e)) 
    "(" 
    (S e)
    ")"
    (S e))
#+END_SRC       

または

#+NAME: 解析木
#+BEGIN_SRC emacs-lisp 
'(S (S e)
    "(" 
    (S e)
    ")"
    (S (S e) "(" (S e) ")" (S e)))
#+END_SRC       

で曖昧になる

*** d)
ababを考える

#+NAME: 解析木
#+BEGIN_SRC emacs-lisp 
'(S a
    (S b (S e) a (S e)) 
    b
    (S e))
#+END_SRC       

#+NAME: 解析木
#+BEGIN_SRC emacs-lisp 
'(S a
    (S e)
    b
    (S a (S e) b (S e)))
#+END_SRC

により曖昧である

*** e 
aaaを考える


#+NAME: 解析木
#+BEGIN_SRC emacs-lisp 
'(S (S (S a)
       (S a)
    (S a)))
#+END_SRC

#+NAME: 解析木
#+BEGIN_SRC emacs-lisp 
'(S (S a)
    (S (S a)
       (S a)))
#+END_SRC

により曖昧である。

** 問題2.2.4

*** a
#+NAME: 
#+BEGIN_SRC 
Expr -> Expr Expr * | Expr Expr - | Expr Expr + | Expr Expr / | num
#+END_SRC

*** b

#+NAME: 
#+BEGIN_SRC 
list -> elem , list | left
#+END_SRC


*** c

#+NAME: 
#+BEGIN_SRC 
list -> list, elem | elem
#+END_SRC

*** d

#+NAME: 
#+BEGIN_SRC BNF
expr -> expr + term | expr - term | term
term -> term * factor | term / factor | factor 
factor -> num | id | ( expr )
#+END_SRC

*** e

#+NAME: 
#+BEGIN_SRC BNF
expr -> expr + term | expr - term | term
term -> term * single | term / single | single
single -> factor | + factor | - factor
factor -> num | id | ( expr )
#+END_SRC

** 問題2.2.5
num -> 11 | 1001| num 0 | num num

1. 11, 1001は3で割きれる。
 11 / 11 = 1 , 1001 / 11 = 11
2. numが3で割り切れるとする
num0は、0をシフトしただけであり、numが割り切ればnum0は割りきれる。
num num も当然3で割りきれる。
よって、numは割りきれる。

**  問題2.2.6
 ローマ数字、は
1 ~ 9 :I, II, III, IV, V, VI, VII, VIII, IX
10 ~ 90 : X, XX, XXX, XL, L, LX, LXX, LXXX, XC
100 ~ 900 : C, CC, CCC, CD, DC, DCC, DCCC, CM
1000 ~ 3000 : M, MM, MMM

 のみである。よって、終端記号は、I, V, X, L,C, D, M である。

#+NAME: 
#+BEGIN_SRC BNF
GreekNum -> FirstRank SecondRank ThirdRank ForthRank
FirstRank -> M | MM  | MMM | e
SecondRank -> C | CC | CCC | CD | DC | DCC | DCCC | CM | e
ThirdRank -> X | XX | XXX | XL | L | LXX | LXXX | XC | e
ForthRank -> I | II | III | IV | V | VLL | VLLL | IX  | e
#+END_SRC

* 2.3の練習問題

** 2.3.1

#+NAME:  
#+BEGIN_SRC BNF
expr -> {printf("+")} expr1 + term 
epxr -> {printf("-"} expr1 - term 
expr -> term        
term -> {printf("*"} term * factor 
term -> {printf("/")} term / factor 
term -> factor 
factor -> {print(1) } 1 
...
factpr -> {print(9) } 9
#+END_SRC

9-5+2の注釈付き解析木
#+NAME:  
#+BEGIN_SRC 
(expr (print +)
      (expr  (print -)
             (term (factor (print 9) 9))
             -
             (term (factor (print 5) 5)))
       +
       (term (factor (print 2) 2)))
#+END_SRC
9-5*2の注釈付き解析木
#+NAME: 
#+BEGIN_SRC 
(expr (print -)
      (term (factor (print 9)))
       -
      (term (print *)
            (factor (print 5) 5)
            *
            (factor (print 2) 2)))
#+END_SRC

** 問題2.3.2


#+NAME:  
#+BEGIN_SRC BNF
expr -> {print (} expr {print +} expr {print )} +
expr -> (print (} expr {print -} expr {print )} -
expr -> expr {print *} expr *
expr -> expr {print /} expr /
expr -> term
term -> (print num) num
#+END_SRC
95-2*
#+NAME:  
#+BEGIN_SRC 
(expr 
    (expr (print "(")
          (expr (term (print 9) 9))
          (print -)
          (expr (term (print 5) 5))
          (print ")")
           -)
     (print *)
     (expr (term (print 2) 2))
     *)
#+END_SRC
952*-
#+NAME:  
#+BEGIN_SRC 
(expr (print "(")
      (expr (term (print 9) 9))
      (print +)
      (expr (expr (term (print 5) 5))
            (print *)
            (expr (term (print 2)))
            *)
      (print ")"))
#+END_SRC

** 問題2.3.3 

#+NAME:  
#+BEGIN_SRC 
thousand -> 1 {print M} hundred
thousand -> 2 {print MM} hundred
thousand -> 3 {print MMM} hundred
thousand -> hundred
hundred -> 1 {print C} ten
hundred -> 2 {print CC} ten
hundred -> 3 {print CCC} ten 
hundred -> 4 {print CD} ten
hundred -> 5 {print D} ten 
hundred -> 6 {print DC} ten 
hundred -> 7 {print DCC} ten
hundred -> 8 {print DCCC} ten
hundred -> 9 {print CM} ten 
hundred -> 0 ten
hundred -> ten
ten -> 1 {print X} ten
ten -> 2 {print XX} ten 
ten -> 3 {print XXX} ten 
ten -> 4 {print XL} ten
ten -> 5 {print L} ten
ten -> 6 {print LX} ten
ten -> 7 {print LXX} ten
ten -> 8 {print LXXX} ten
ten -> 9 {print XC} ten
ten -> 0 one
ten -> one
one -> 1 {print I}
one -> 2 {print II}
one -> 3 {print III}
one -> 4 {print IV}
one -> 5 {print V}
one -> 6 {print VI}
one -> 7 {print VII}
one -> 8 {print VIII}
one -> 9 {print IX}
one -> 0
#+END_SRC

** 問題2.3.4

#+NAME: 
#+BEGIN_SRC 
RomaNum -> thousand 
RomaNum -> hundred
RomaNum -> ten 
RomaNum -> one
thousand -> thousandRank hundred
thousand -> thousandRank {print 0} ten
thousand -> thousandRank {print 0} {print 0} one
thousand -> thousandRank {print 0} {print 0} {print 0}
hundred -> hundredRank ten one 
hundred -> hundredRank {print 0} one
hundred -> hundredRank {print 0} {print 0}
ten -> tenRank one 
ten -> tenRank {print 0}
one -> oneRank
thousandRank -> M    {print 1}
thousandRank -> MM   {print 2}
thousandRank -> MM   {print 3}
hundredRank  -> C    {print 1}
hundredRank  -> CC   {print 2} 
hundredRank  -> CCC  {print 3}  
hundredRank  -> CD   {print 4}  
hundredRank  -> D    {print 5}  
hundredRank  -> DC   {print 6}  
hundredRank  -> DCC  {print 7}  
hundredRank  -> DCCC {print 8}  
hundredRank  -> CM   {print 9}  
tenRank      -> X    {print 1}
tenRank      -> XX   {print 2}
tenRank      -> XXX  {print 3}
tenRank      -> XL   {print 4}
tenRank      -> L    {print 5}
tenRank      -> LX   {print 6}
tenRank      -> LXX  {print 7}
tenRank      -> LXXX {print 8}
oneRank      -> XC   {print 9}
oneRank      -> I    {print 1}
oneRank      -> II   {print 2}
oneRank      -> III  {print 3}
oneRank      -> IV   {print 4}
oneRank      -> V    {print 5}
oneRank      -> VI   {print 6}
oneRank      -> VII  {print 7}
oneRank      -> VIII {print 8}
oneRank      -> IX   {print 9}
#+END_SRC

** 問題2.3.5
#+NAME: 
#+BEGIN_SRC
expr -> {print op} expr expr op 
expr -> {print num} num 
#+END_SRC

